### ISSUE TITLE
Limitation of sending more than 2GB data inter process

### ISSUE THREAD

**Issue by GreatYYX** [usc-isi-i2/paralyzer#1]
MapReduce model doesn't support exchanging more than 2GB data between processes on MacOS. It causes failure while fetching reduced data.

```
Process Process-1:
Traceback (most recent call last):
  File "/<hidden-path>/Github/iswc-2019-tabular-data-challenge/create_wikidata_dictionaries.py", line 94, in <module>
  File "/<hidden-path>/Github/iswc-2019-tabular-data-challenge/iswc_env/lib/python3.6/site-packages/pyrallel/map_reduce.py", line 129, in join
    result = self._result_queue.get()
  File "/<hidden-path>/anaconda3/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/<hidden-path>/anaconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/<hidden-path>/anaconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/<hidden-path>/anaconda3/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
  File "/<hidden-path>/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/<hidden-path>/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/<hidden-path>/Github/iswc-2019-tabular-data-challenge/iswc_env/lib/python3.6/site-packages/pyrallel/map_reduce.py", line 192, in _run_manager
    self._result_queue.put(self._reducer_queue.get())
  File "/<hidden-path>/anaconda3/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/<hidden-path>/anaconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/<hidden-path>/anaconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/<hidden-path>/anaconda3/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
```
https://github.com/usc-isi-i2/pyrallel/blob/50097e12c48592967fe227c74fb66b80d2a18fc5/pyrallel/map_reduce.py#L192

https://github.com/python/cpython/pull/9027 A bug report here is about WinAPI. But this only works on Windows. Also, `DWORD` is 32bits, it still can not exchange more than 4GB data.

**Comment by GreatYYX** [comment]
Possible solutions:
1. Enhance queue implementation, or replace builtin multiprocessing queue by other queue services (but this require user to install additional packages).
2. When data size is huge, write to temporary file system. Disk IO is the bottleneck.
3. Chunk data into small pieces. But there could be multiple senders of a queue. It (probably both manager and sender) needs to dispatch all chunks belong to the same sender to same receiver, and receiver needs to hold and assemble chunks.
