### ISSUE TITLE
ParallelProcessor.join() Fails

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/paralyzer#17]
Traceback (most recent call last):
  File "/nas/home/rogers/kgtk/github/kgtk/kgtk/cli/import_wikidata.py", line 2912, in run
    pp.join()
  File "/nas/home/rogers/.conda/envs/kgtk-env/lib/python3.8/site-packages/pyrallel/parallel_processor.py", line 389, in join
    q.join_thread()
  File "/nas/home/rogers/.conda/envs/kgtk-env/lib/python3.8/multiprocessing/queues.py", line 146, in join_thread
    assert self._closed, "Queue {0!r} not closed".format(self)
AssertionError: Queue <pyrallel.queue.ShmQueue object at 0x7efe0c08aca0> not closed

**Comment by CraigMiloRogers** [comment]
The problem invovles a q.join_thread() call that was added on 11-Feb-2021: "fix progress status queue has None object, update status monitoring or collector and progress queuef"
