### ISSUE TITLE
ShmQueue: Unpickling Error

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/paralyzer#5]
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rogers/elicit/github/kgtk2/kgtk/cli/import_wikidata.py", line 1102, in run
    action, nrows, erows, qrows, header = collector_q.get()
  File "/home/rogers/.local/lib/python3.8/site-packages/pyrallel/queue.py", line 238, in get
    msg = self.serializer.loads(b''.join(self.buf_msg_body))
_pickle.UnpicklingError: pickle data was truncated

**Comment by CraigMiloRogers** [comment]
The error is guaranteed to occur, but not at the same place.

**Comment by CraigMiloRogers** [comment]
put: msg_id=b'145a18bca01b' msg_size=5299 chunk_id=1 total_chunks=1.
get: msg_id=b'145a18bca01b' msg_id2=b'145a18bca01b' msg_size=4206 chunk_id=1 total_chunks=1.

Maybe there's a cache flushing problem?

**Comment by CraigMiloRogers** [comment]
I think I have this straightened out.  There were errors in multi-chunk message processing, and my initial fix led to a timing problem.
